name: Dependency report update

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }} 
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '17'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'gradle'
    - name: Create license report
      run: |
        ./gradlew generateLicenseReport
        sed -i '/<p id="timestamp">/,/<\/p>/d' docs/licenses/index.html
    - name: Add imprint
      run: |
        sed -i '/<\/body>/i <p> <a href="https://michaeltroger.com/imprint">Imprint / Impressum / Aviso legal / Mentions légales / Informazioni legali / Informações legais</a></p>' docs/licenses/index.html
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        branch: feature/update_dependency_report
        title: Update of dependency report
        commit-message: Update of dependency report
        add-paths: |
          docs/licenses/*
